------------------------------------------------------------------------ r2792 | loera01 | 2010-04-15 17:45:15 +0100 (Thu, 15 Apr 2010) | 20 lines
ODBC applications using the Windows driver manager are redirected to use the
Unicode version of ODBC functions that use string arguments, regardless of
whether the original code specifies the Unicode version.  SQLExecDirect() and
SQLPrepare() are therefore executed as SQLExecDirectW() and SQLPrepareW(),
respectively.

The Ingres ODBC driver reverts the Unicode strings back to multi-byte, and
uses the API function IIapi_convertData() to perform the conversion.  Since
the source and destination strings are described as an IIAPI_DATAVALUE, the
string lengths are u_i2.  The max value of a u_i2 is only 65535, or
approximately 64K.  For UCS2 (two-byte) Unicode strings, this means that
queries of only 32K can be converted at one time.

I revised the ExecDirectOrPrepareW() function, which converts the query
strings to multi-byte, to look for strings greater than 64 bytes in length.
If this threshhold is exceeded, ExecDirectOrPrepareW() converts the query
string in 64-byte segments before calling SQLExecDirect_InternalCall() or
SQLPrepare_InternalCall().

------------------------------------------------------------------------
r2793 | bonro01 | 2010-04-15 22:25:56 +0100 (Thu, 15 Apr 2010) | 1 line

Fix Usage error when calling set_env.sh
------------------------------------------------------------------------

diff --git a/buildtools/createdbms b/buildtools/createdbms
--- a/buildtools/createdbms
+++ b/buildtools/createdbms
@@ -20,6 +20,10 @@
 ##	    they are now set in the build environment.
 ##	24-Mar-2010 (frima01)
 ##	    Removed function keyword - not supported on all systems.
+##	15-Apr-2010 (bonro01)
+##	    Move set_env.sh call and use set -- to clear $1 parm before
+##	    calling the set_env.sh script so that createdbms parms
+##	    are not passed to sourced scripts.
 
 usage()
 {
@@ -102,23 +106,6 @@ then
 fi
 export BUILDTOOLS
 
-if [ -f ${BUILDTOOLS}/set_env.sh ]
-then
-  . ${BUILDTOOLS}/set_env.sh
-else
-  echo "Error, I cannot find the set_env.sh script"
-  echo "This is required to use createdbms"
-  echo "Please run createdbms from the root directory of the Ingres source"
-  exit 1
-fi
-
-# Verify ING_ROOT was set, should be by the set_env.sh call above.
-if [ -z "$ING_ROOT" ]
-then
-    echo "ING_ROOT must be set to run this script"
-    exit 1
-fi
-
 unames=`uname -s`
 unamem=`uname -m`
 
@@ -141,6 +128,27 @@ then
 fi
 
 export II_INSTALLATION
+
+# Clear $1 argument parms so that they are not passed
+# to sourced scripts.
+set --
+
+if [ -f ${BUILDTOOLS}/set_env.sh ]
+then
+  . ${BUILDTOOLS}/set_env.sh
+else
+  echo "Error, I cannot find the set_env.sh script"
+  echo "This is required to use createdbms"
+  echo "Please run createdbms from the root directory of the Ingres source"
+  exit 1
+fi
+
+# Verify ING_ROOT was set, should be by the set_env.sh call above.
+if [ -z "$ING_ROOT" ]
+then
+    echo "ING_ROOT must be set to run this script"
+    exit 1
+fi
 
 # Create version information to find the appropriate tar file to install from.
 if [ ! -f $ING_ROOT/build/version.rel ]
